# PROJECT: GRAM-SCHMIDT
## Name: LÊ VÕ MINH PHƯƠNG
## Student ID: 22120286
## Subject: Toán Ứng dụng Thống kê
## Class: 22_3

#I. GRAM - SCHMIDT ALGORITHM FOR $QR$ DECOMPOSITION
**$QR$ Decomposition using Gram - Scmidt algorithm**

Given a matrix $ A $ of size $ m \times n $ (where $ m \geq n $), we want to decompose it into $ A = QR $, where $ Q $ is an orthogonal matrix of size $ m \times n $ and $ R $ is an upper triangular matrix of size $ n \times n $.

1. **Initialize Matrices:**
   - Initialize matrix $ Q $ of size $ m \times n $ and matrix $ R $ of size $ n \times n $ with zeros.

2. **Iterate over Columns of $ A $:**
   For each column $ k $ of $ A $, do the following steps 3 and 4:
   
3. **Compute $ k $-th Columns of $ Q $:**
   - Extract the $ k $-th column of $ A $ and denote it as $ a_k $.
   - Subtract the projection of $ a_k $ onto the already computed columns of $ Q $ from $ a_k $:  
     $$ v_{k} = a_{k} - \sum_{j=1}^{k-1} \frac{q_j^T a_k}{||q_j||^2} q_j $$
   - Normalize $ v_k $ to obtain the $ k $-th column of $ Q $:  
     $$ q_{k} = \frac{v_{k}}{||v_{k}||} $$

4. **Compute Elements of $ R $:**
   - Compute the diagonal elements of $ R $:
   $$ R_{ii} = || v_i || $$
   - Compute the off-diagonal elements of $ R $:  
      $$R_ij = q_i^T . a_j $$

5. **Repeat:**
   - Repeat steps 3 and 4 for all columns of $ A $ until all columns have been processed.

6. **Output:**
   - The matrix $ Q $ contains the orthonormal columns of $ A $.
   - The upper triangular matrix $ R $ contains the coefficients of the linear combinations of the columns of $ Q $ that reconstruct $ A $.


# II. Implement functions to perform QR decomposition

## 1. Check if a matrix is QR decomposition possible

In [1]:
!pip install numpy # install numpy if haven't

In [2]:
!pip install scipy #install scipy if haven't

In [3]:
import numpy as np
#from scipy.linalg import qr

def is_qr_possible(A):
    A=np.array(A)
    #Check if A is full rank
    if np.linalg.matrix_rank(A) < min(A.shape):
        print("QR decomposition is not possible: Matrix is not full rank (linearly dependent).")
        return False

    print("QR decomposition is possible for input Matrix.")
    return True

# Test with a matrix A
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = is_qr_possible(A)



QR decomposition is not possible: Matrix is not full rank (linearly dependent).


## 2. Write function to calculate the norm of a vector

In [4]:
def calculate_Euclidean_norm (vector):
  norm = 0
  for i in vector:
    norm += i*i
  return norm**0.5


## 3. Write function to round entries of a matrix

In [5]:
def round_matrix_entries(matrix:list, decimals:int):
    for i in range(len(matrix)):
        tmp=matrix[i]
        for k in range(len(tmp)):
            tmp[k]=round(tmp[k],decimals)
        matrix[i]=tmp
    return matrix

## 4. Write function to initialize matrix with all 0

In [6]:
def zeros(m, n):# set 0 values for matrices Q and R
    res = []
    for i in range (m):
      res.append ([0]*n)
    return res

## 3. Write function to perform QR decomposition

In [7]:
def qr_decomposition(A):

    # Check if QR decomposition is possible at the beginning to avoid unnecessay step below
    if not is_qr_possible(A):
        return None, None

    num_rows = len(A)
    num_columns = len(A[0])
    Q = zeros(num_rows, num_columns)
    R = zeros(num_columns, num_columns)

    for k in range(num_columns):
        #construct the main diagonal
        R[k][k] = calculate_Euclidean_norm([A[i][k] for i in range(num_rows)])

        #check if A's columns linear dependent as their norm is 0 (on the diag of R matrix)
        if R[k][k] < 1e-10:
            raise ValueError("Column vectors are not linear independent!")

        else:
            #calculate the entries for Q matrix
            for i in range(num_rows):
                Q[i][k] = A[i][k] / R[k][k] # R[k][k] is the norm of vectors

        for j in range(k + 1, num_columns):
            R[k][j] = sum(Q[i][k] * A[i][j] for i in range(num_rows))
            for i in range(num_rows):
                A[i][j] = A[i][j] - Q[i][k] * R[k][j]
    return Q, R


# III. TEST THE PROGRAM AND USE BUILT-IN FUNCTION TO COMPARE THE RESULTS

## 1. Test the program

### 1.1 Test with impossible QR decompositon matrix

In [8]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1, 2, 3], [2, 4, 6], [1, 3, 5]]

Q, R = qr_decomposition(A)

print("Q:\n",Q)
print("R:\n", R)

QR decomposition is not possible: Matrix is not full rank (linearly dependent).
Q:
 None
R:
 None


### 1.2 Test with possible QR decomposition matrices

In [10]:
C = [[1, 1, 2], [2, -1, 1], [-2, 4, 1]]
D = [[-1,-1,1], [1,3,3],[-1,-1,5],[1,3,7]]

matrix_test = [[1,1,1], [2,2,0],[3,0,0],[0,0,1]]
print ('Original matrix:\n', np.array(matrix_test))

Q, R = qr_decomposition(matrix_test)

#round entries of matrix (if needed)
#round_matrix_entries(Q,7)
#round_matrix_entries(R,7)

# convert to np.array for 'cleaner' format to display (not displaying commas as list)

print("Q:\n",np.array(Q))
print("R:\n", np.array(R))

#multiply the resutl to check if the decomposition correct
checkMatrix = np.array(Q) @ np.array (R)
round_matrix_entries(checkMatrix,1)
print ("Check matrix:\n",checkMatrix)



Original matrix:
 [[1 1 1]
 [2 2 0]
 [3 0 0]
 [0 0 1]]
QR decomposition is possible for input Matrix.
Q:
 [[ 2.67261242e-01  3.58568583e-01  5.96284794e-01]
 [ 5.34522484e-01  7.17137166e-01 -2.98142397e-01]
 [ 8.01783726e-01 -5.97614305e-01  2.06877846e-17]
 [ 0.00000000e+00  0.00000000e+00  7.45355992e-01]]
R:
 [[3.74165739 1.33630621 0.26726124]
 [0.         1.79284291 0.35856858]
 [0.         0.         1.34164079]]
Check matrix:
 [[ 1.  1.  1.]
 [ 2.  2.  0.]
 [ 3. -0.  0.]
 [ 0.  0.  1.]]


*Comment*: After multiplying the Q and R matrices, we get the original matrix.

## 2. Compare result with `numpy.linalg.qr()`, `scipy.linalg.qr()` and `torch.linalg.qr()` methods to compare the results

### 2.1 Impossibly decompose

In [18]:
Q_test, R_test = np.linalg.qr (B)

print ('Q_numpy:\n',Q_test,'\n\n','R_numpy:\n',R_test)

Q_numpy:
 [[-4.08248290e-01 -1.82574186e-01 -8.94427191e-01]
 [-8.16496581e-01 -3.65148372e-01  4.47213595e-01]
 [-4.08248290e-01  9.12870929e-01  1.05471187e-15]] 

 R_numpy:
 [[-2.44948974e+00 -5.30722778e+00 -8.16496581e+00]
 [ 0.00000000e+00  9.12870929e-01  1.82574186e+00]
 [ 0.00000000e+00  0.00000000e+00  1.55431223e-15]]


*Comment*: Even if a matrix is not full rank (i.e., it has linearly dependent columns), `np.linalg.qr` can still return a $QR$ decomposition. This is because the function uses a numerical method that can handle small numerical errors and round-off issues that might make a matrix appear to be not full rank in a computer’s floating-point arithmetic. The resulting $Q$ and $R$ matrices might not be exactly orthogonal or upper triangular due to these numerical issues, but they will be close in the sense of numerical approximation.

### 2.2 Possibly decompose

### 2.2.1 Use `numpy.linalg.qr()` and `scipy.linalg.qr()`

In [11]:
import scipy as sp

C = [[1, 1, 2], [2, -1, 1], [-2, 4, 1]]
D = [[-1,-1,1], [1,3,3],[-1,-1,5],[1,3,7]]

print ("Original matrix:\n", np.array(C))
Q, R = qr_decomposition(C)
#round entries of matrix (if needed for a easier-to-see format)
round_matrix_entries(Q,10)
round_matrix_entries(R,10)

# convert to np.array for 'cleaner' format to display (not displaying commas as list)

print("Q:\n",np.array(Q))
print("R:\n", np.array(R))

#check by multiplying A=QR
print ("Check by Q@R:")
checkResult= np.array(Q) @ np.array(R)
print (checkResult,'\n')


#-------------numpy--------------------
print ("The result of numpy method:")
C = [[1, 1, 2], [2, -1, 1], [-2, 4, 1]]
D = [[-1,-1,1], [1,3,3],[-1,-1,5],[1,3,7]]
Q_numpy, R_numpy = np.linalg.qr (np.array(C))

#round entries in the matrices
round_matrix_entries(Q_numpy,10)
round_matrix_entries(R_numpy,10)
print ('Q_numpy:\n',Q_numpy,'\n\n','R_numpy:\n',R_numpy)

#-------------scipy--------------------
print ("\nThe result of scipy method:")
Q_scipy, R_scipy = sp.linalg.qr (np.array(C))

#round entries in the matrices
round_matrix_entries(Q_scipy,10)
round_matrix_entries(R_scipy,10)
print ('Q_scipy:\n',Q_scipy,'\n\n','R_scipy:\n',R_scipy)




Original matrix:
 [[ 1  1  2]
 [ 2 -1  1]
 [-2  4  1]]
QR decomposition is possible for input Matrix.
Q:
 [[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]
R:
 [[ 3.         -3.          0.66666667]
 [ 0.          3.          2.33333333]
 [ 0.          0.          0.33333333]]
Check by Q@R:
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]] 

The result of numpy method:
Q_numpy:
 [[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]] 

 R_numpy:
 [[-3.          3.         -0.66666667]
 [ 0.         -3.         -2.33333333]
 [ 0.          0.          0.33333333]]

The result of scipy method:
Q_scipy:
 [[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]] 

 R_scipy:
 [[-3.          3.         -0.66666667]
 [ 0.         -3.         -2.33333333]
 [ 0.          0.          0.33333333]]


*Comment*: The sign minus $-$ in the Q and R matrices of two ways and my implementation are not identical but it is stills correct as $A$ is exactly equals to $Q R $ as there are multiple valid QR decompositions for a given matrix (check as below). Specifically, the sign of the columns of matrix $Q$ can be multiplied by any scalar, and the result will still be a valid orthogonal matrix. Similarly, the signs of the elements of matrix
$R$ can be adjusted without affecting the validity of the $QR$ decomposition.
The differences in sign are just a result of different conventions or implementation details.

In [12]:
print ("Original matrix:\n", np.array(C))
print ("\nCheck result of numpy:")
check_numpy = Q_numpy@ R_numpy
print (check_numpy)
print ("\nCheck result of scipy:")
check_scipy = Q_scipy@ R_scipy
print (check_scipy)

Original matrix:
 [[ 1  1  2]
 [ 2 -1  1]
 [-2  4  1]]

Check result of numpy:
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]]

Check result of scipy:
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]]


### 2.2.2 Use `torch.linalg.qr()` to compare

In [13]:
!pip install torch #intall torch if it hasn't been installed

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [16]:
E = [[-2,1,3], [1,0,0],[0,1,0], [0,0,1]]

print ("Original matrix:\n", np.array(E))
Q, R = qr_decomposition(E)
#round entries of matrix (if needed)
#round_matrix_entries(Q,7)
#round_matrix_entries(R,7)

print("Q:\n",np.array(Q))
print("R:\n", np.array(R))
res = np.array(Q)@np.array(R)
print ("Check Q@R:\n")
print(round_matrix_entries(res,1))

Original matrix:
 [[-2  1  3]
 [ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]]
QR decomposition is possible for input Matrix.
Q:
 [[-0.89442719  0.18257419  0.31622777]
 [ 0.4472136   0.36514837  0.63245553]
 [ 0.          0.91287093 -0.31622777]
 [ 0.          0.          0.63245553]]
R:
 [[ 2.23606798 -0.89442719 -2.68328157]
 [ 0.          1.09544512  0.54772256]
 [ 0.          0.          1.58113883]]
Check Q@R:

[[-2.  1.  3.]
 [ 1. -0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [17]:
import torch
from torch import tensor

E = [[-2,1,3], [1,0,0],[0,1,0], [0,0,1]]
E_tensor = torch.tensor(E, dtype=torch.float)

# Perform QR decomposition
Q_tensor, R_tensor = torch.linalg.qr(E_tensor)
print ('Q_tensor: \n', Q_tensor)
print ('R_tensor: \n', R_tensor)

check_tensor=Q_tensor@R_tensor
print ("Check tensor:\n", check_tensor)

Q_tensor: 
 tensor([[-0.8944, -0.1826,  0.3162],
        [ 0.4472, -0.3651,  0.6325],
        [ 0.0000, -0.9129, -0.3162],
        [ 0.0000, -0.0000,  0.6325]])
R_tensor: 
 tensor([[ 2.2361, -0.8944, -2.6833],
        [ 0.0000, -1.0954, -0.5477],
        [ 0.0000,  0.0000,  1.5811]])
Check tensor:
 tensor([[-2.0000e+00,  1.0000e+00,  3.0000e+00],
        [ 1.0000e+00,  8.9407e-08,  2.6879e-07],
        [ 0.0000e+00,  1.0000e+00,  4.4419e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])


*Comment:* The difference in the $Q$ and $R$ matrices between my implementation and `np.linalg.qr()`, `sp.linalg.qr()` and `torch.linalg.qr()` likely arises from the fact that they use a different algorithm or implementation details that may result in different numerical precision or handling of certain cases, the result from `torch.linalg.qr()` seems to have result different from other methods as it's automatically rounded to 4 digits after comma. However, after checking by multiplying $QR$, we always get the original matrix.


# IV. APPLICATIONS OF QR DECOMPOSITION

## 1. Compute Inverse Matrix:
To compute the inverse of a matrix $A$ using its QR decomposition, we use the formula:

$$ A^{-1} = R^{-1} Q^T $$

Where:
- $A$ is the original matrix.
- $Q$ is the orthogonal matrix from the QR decomposition of $A$.
- $R$ is the upper triangular matrix from the QR decomposition of $A$.
- $R^{-1}$ is the inverse of the upper triangular matrix $R$.
- $Q^T$ is the transpose of the orthogonal matrix $Q$.  

## 2. Solving Linear Least Squares Problems
QR decomposition is used to solve linear least squares problems efficiently. Here's how it's done:

- Given a linear system $Ax = b$ where $A$ is an $m \times n$ matrix (with $m \geq n$), $x$ is an $n \times 1$ vector of unknowns, and $b$ is an $m \times 1$ vector of constants.

-  If the system $Ax = b$ is overdetermined (i.e., there are more equations than unknowns), there may not be an exact solution. In such cases, we seek the "best" solution in terms of minimizing the sum of squared residuals, which leads to the least squares problem.

- To solve the least squares problem, we first perform QR decomposition on matrix $A$ to obtain $A = QR$, where $Q$ is an $m \times n$ orthogonal matrix and $R$ is an $n \times n$ upper triangular matrix.

- We can then rewrite the original system as $Rx = Q^Tb$. Since $R$ is upper triangular, this system can be efficiently solved using back substitution.

- After obtaining the solution $x$, we have the best-fit solution to the least squares problem.

By using QR decomposition, we transform the original linear least squares problem into an equivalent problem with a triangular matrix, making it computationally efficient to solve.

## 3. Image compression:
QR decomposition can be utilized in image compression techniques to reduce the size of an image while preserving its essential features. By representing the image matrix as a product of an orthogonal matrix $Q$ and an upper triangular matrix $R$, the original image can be approximated with fewer coefficients. This reduction in data size can lead to more efficient storage and transmission of images.


# V. FUNCTIONS' DESCRIPTION
- `is_qr_possible(A)`: check at first if the given A matrix possible for $QR$ decomposition on the cases when the vector are not linearly independent.
- `calculate_Euclidean_norm (vector)`: return the Euclidean norm of a vector.
- `round_matrix_entries(matrix:list, decimals:int)`: used to round all entries of a matrix with `decimals` digits after comma.
- `zeros(m, n)`: initialize the $0$ matrix for $Q$ and $R$  matrices.
- `qr_decomposition(A)`: the main function to perform $QR$ decomposition, return the $Q$ and $R$ matrices (if possible) or return None (if impossible). The implementation uses exactly Gram - Schmidt algorithm presented above.

$$ This \space is \space the \space end \space of \space the \space Project. $$